// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __gwassim_RcppExports_h__
#define __gwassim_RcppExports_h__

#include <Rcpp.h>

namespace gwassim {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("gwassim", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("gwassim", "gwassim_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in gwassim");
            }
        }
    }

    inline std::vector<int> traverse_cor(NumericMatrix x, float maxcor) {
        typedef SEXP(*Ptr_traverse_cor)(SEXP,SEXP);
        static Ptr_traverse_cor p_traverse_cor = NULL;
        if (p_traverse_cor == NULL) {
            validateSignature("std::vector<int>(*traverse_cor)(NumericMatrix,float)");
            p_traverse_cor = (Ptr_traverse_cor)R_GetCCallable("gwassim", "gwassim_traverse_cor");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_traverse_cor(Rcpp::wrap(x), Rcpp::wrap(maxcor));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<std::vector<int> >(__result);
    }

}

#endif // __gwassim_RcppExports_h__
