# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

traverse_cor <- function(x, maxcor) {
    .Call('gwassim_traverse_cor', PACKAGE = 'gwassim', x, maxcor)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('gwassim_RcppExport_registerCCallable', PACKAGE = 'gwassim')
})
