# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gatesHelper_ <- function(mat) {
    .Call('gwassim_gatesHelper_', PACKAGE = 'gwassim', mat)
}

traverse_cor <- function(x, maxcor) {
    .Call('gwassim_traverse_cor', PACKAGE = 'gwassim', x, maxcor)
}

get_chol <- function(A) {
    .Call('gwassim_get_chol', PACKAGE = 'gwassim', A)
}

rmvnorm_ <- function(n, mu, sigma) {
    .Call('gwassim_rmvnorm_', PACKAGE = 'gwassim', n, mu, sigma)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('gwassim_RcppExport_registerCCallable', PACKAGE = 'gwassim')
})
